name: Release

on:
  push:
    tags: ["v*"]
    branches:
      - master
      - dev_lab_01

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lab_01/requirements.txt
        pip install setuptools wheel
    - name: Build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd lab_01
        python setup.py sdist bdist_wheel
        python ../.github/publish_release.py
